apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  steps:
    - name: say-goodbye
      image: docker.io/library/python:alpine
      command:
        - python
      args:
        - "-c"
        - "print('Goodbye')"
