apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process
spec:
  steps:
    - name: clone-repo
      image: alpine/git
      args:
        - clone
        - https://github.com/equinor/radix-sub-pipeline-example
        - -b
        - pipeline-with-multiple-task-steps
        - /var/source
      volumeMounts:
        - name: source-volume
          mountPath: /var/source

    - name: check
      image: alpine
      script: |
        #!/usr/bin/env sh
        ls -la /var/source
      volumeMounts:
        - name: source-volume
          mountPath: /var/source
  volumes:
    - name: source-volume
      emptyDir: {}
