apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process
spec:
  steps:
    - name: clone-repo
      image: alpine/git
      args:
        - clone
        - https://github.com/equinor/radix-sub-pipeline-example
        - -b
        - pipeline-with-multiple-task-steps
        - /var/source
      volumeMounts:
        - name: source-volume
          mountPath: /var/source
      onError: continue

    - image: ubuntu
      script: |
        #!/usr/bin/env bash
        ls -la /var/source
        cat /var/source/radixconfig.yaml
      volumeMounts:
        - name: source-volume
          mountPath: /var/source
      onError: continue

  volumes:
    - name: source-volume
      emptyDir: {}
