apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-example-with-env-vars
spec:
  params:
    - name: VAR1               #it must be set in the radixconfig.yaml
    - name: VAR2               #it can be set in the radixconfig.yaml, if not - used default "not-set-var2"
      default:
        type: string
        stringVal: not-set-var2
    - name: VAR3               #it can be set in the radixconfig.yaml, if not - used default "not-set-var3"
      default:
        type: string
        stringVal: not-set-var3
    - name: CONNECTION_STRING  #it must be set in the radixconfig.yaml
    - name: PROD_USER          #it can be set in the radixconfig.yaml, if not - used default empty string
      default:
        type: string
        stringVal: ""
  tasks:
    - name: show-env-vars      #name of the task "env-vars-list" in this pipeline
      params:
        - name: VAR1T          #set by parameter VAR1, from the radixconfig.yaml
          value:
            type: string
            stringVal: $(params.VAR1)
        - name: VAR2T          #set by parameter VAR2, from the radixconfig.yaml or used default "not-set-var2"
          value:
            type: string
            stringVal: $(params.VAR2)
        - name: VAR3T          #set by parameter VAR3, not set in the radixconfig.yaml - used default "not-set-var3"
          value:
            type: string
            stringVal: $(params.VAR3)
        - name: VAR4T          #set explicitly with the value "value4"
          value:
            type: string
            stringVal: value4
        - name: CONNECTION_STRING #set by parameter CONNECTION_STRING, from the radixconfig.yaml
          value:
            type: string
            stringVal: $(params.CONNECTION_STRING)
        - name: PROD_USER         #set by parameter PROD_USER, from the radixconfig.yaml
          value:
            type: string
            stringVal: $(params.PROD_USER)
      taskRef:
        name: env-vars-list    #task name