apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-multiple-steps
spec:
  tasks:
    - name: show-hello
      taskRef:
        name: hello

    - name: show-goodbye
      runAfter:
        - show-numbers
        - show-letters
      taskRef:
        name: goodbye

    - name: show-letters
      runAfter:
        - show-hello
      taskRef:
        name: letters
    - name: show-numbers
      runAfter:
        - show-hello
      taskRef:
        name: numbers
