apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-multiple-steps
spec:
  tasks:
    - name: task-example-hello
      taskRef:
        name: hello

    - name: task-example-goodbye
      runAfter:
        - task-example-numbers
        - task-example-letters
      taskRef:
        name: goodbye

    - name: task-example-letters
      runAfter:
        - hello
      taskRef:
        name: letters
    - name: task-example-numbers
      runAfter:
        - hello
      taskRef:
        name: numbers
