apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-example-with-secrets
spec:
  tasks:
    - name: use-secrets-for-db      #name of the task "use-secrets" in this pipeline
      taskRef:
        name: use-secrets    #task name