apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-multiple-steps
spec:
  tasks:
    - name: task-example-hello
      taskRef:
        name: hello

    - name: task-example-goodbye
      runAfter:
        - say-numbers
        - say-letters
      taskRef:
        name: goodbye

    - name: say-letters
      runAfter:
        - hello
      taskRef:
        name: letters
    - name: say-numbers
      runAfter:
        - hello
      taskRef:
        name: numbers
