apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-example-with-env-vars
spec:
  params:
    - name: VAR1
    - name: VAR2
      type: string
      default: not-set-var2
    - name: VAR3
      type: string
      default: not-set-var3
  tasks:
    - name: show-env-vars
      params:
        - name: VAR1T
          value: $(params.VAR1)
        - name: VAR2T
          value: $(params.VAR2)
        - name: VAR3T
          value: $(params.VAR3)
        - name: VAR4T
          value: value4
      taskRef:
        name: env-vars-list