apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-multiple-task-steps
spec:
  tasks:
    - name: show-hello
      taskRef:
        name: hello

    - name: show-goodbye
      runAfter:
        - show-numbers
        - show-letters
      taskRef:
        name: goodbye

    - name: perform-process
      runAfter:
        - show-hello
      taskRef:
        name: process
