apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: radix-task-1
  namespace: radix-sub-pipeline-example-app
spec:
  steps:
    - name: show-secrets
      image: alpine
      env:
        - name: DB_SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: $(radix.build-secrets)
              key: DB_SERVER
      envFrom:
        - secretRef:
            name: $(radix.build-secrets)
          prefix: BUILD_SECRET_
      script: |
        #!/usr/bin/env sh
        printenv | grep "DB"
        
        echo "--- /var/*-volume"
        ls -la /var/*-volume
        
        echo "--- /var/pass-volume/password.txt"
        cat /var/pass-volume/password.txt
        
        echo "--- /var/cert-volume/priv/cert.key"
        cat /var/cert-volume/priv/cert.key|head -n 3
        
        echo "--- /var/cert-volume/priv/cert.pub"
        cat /var/cert-volume/priv/cert.pub|head -n 3
        :
      volumeMounts:
        - name: volume-with-password
          mountPath: /var/pass-volume          #mount this volume to a folder "/var/task-volume"
        - name: volume-cert
          mountPath: /var/cert-volume          #mount this volume to a folder "/var/task-volume"
  volumes:
    - name: volume-with-password  #a volume, which can be shared between task steps
      secret:
        secretName: $(radix.build-secrets)
        items:
          - key: DB_PASSWORD
            path: password.txt
    - name: volume-cert
      secret:
        secretName: $(radix.build-secrets)
        items:
          - key: CERT_PRIV_KEY
            path: priv/cert.key
          - key: CERT_PUB_KEY
            path: priv/cert.pub