apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: use-secrets
spec:
  steps:
    - name: show-secrets
      image: alpine
      script: |
        #!/usr/bin/env sh
        printenv | grep "DB"
